# Generated by Django 6.0.7 on 2026-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_de_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
