# Generated by Django 6.0.7 on 2026-08-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintura',
            name='nro_pintura',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
