# Generated by Django 6.0.7 on 2026-08-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pintura_nro_pintura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pintura',
            name='nro_pintura',
            field=models.IntegerField(unique=True),
        ),
    ]
